# Generated by Django 6.1.1 on 2026-09-24 23:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Destino',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(db_column='tx_categoria', max_length=100, verbose_name='Categoria')),
                ('endereco', models.TextField(db_column='tx_endereco', verbose_name='Endereco')),
                ('descricao', models.TextField(db_column='tx_descricao', verbose_name='Descricao')),
            ],
            options={
                'verbose_name': 'Destino',
                'verbose_name_plural': 'Destino',
                'db_table': 'destino',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(db_column='tx_username', max_length=100, unique=True, verbose_name='Username')),
                ('email', models.EmailField(db_column='tx_email', max_length=100, verbose_name='Email')),
                ('senha', models.CharField(db_column='tx_senha', max_length=1000, unique=True)),
                ('nome_completo', models.CharField(db_column='tx_nome_completo', max_length=1000, unique=True, verbose_name='Nome Completo')),
                ('ta_ativo', models.BooleanField(db_column='fl_ta_ativo', default=False, verbose_name='Ativo')),
                ('data_entrada', models.DateTimeField(db_column='dt_data_login', unique=True, verbose_name='Data de entrada')),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
                'db_table': 'usuario',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Descarte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_criacao', models.DateTimeField(db_column='dt_data_criacao', unique=True, verbose_name='Data de criacao')),
                ('peso_estimado_kg', models.FloatField(db_column='vl_peso_estimado_kg', unique=True, verbose_name='Peso Estimado')),
                ('categoria', models.CharField(db_column='tx_categoria', max_length=100, verbose_name='Categoria')),
                ('input_do_usuario', models.TextField(db_column='tx_input_do_usuario', max_length=1000, unique=True, verbose_name='Input do Usuario')),
                ('Destino', models.ForeignKey(db_column='destino_id', on_delete=django.db.models.deletion.CASCADE, related_name='descarte', to='EcoRota.destino', verbose_name='Destino')),
                ('Usuario', models.ForeignKey(db_column='usuario_id', on_delete=django.db.models.deletion.CASCADE, related_name='descarte', to='EcoRota.usuario', verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Descarte',
                'verbose_name_plural': 'Descarte',
                'db_table': 'descarte',
                'managed': True,
            },
        ),
    ]
