# Generated by Django 6.1.1 on 2026-09-27 00:53

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('EcoRota', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Destino',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(db_column='tx_categoria', max_length=100, verbose_name='Categoria')),
                ('endereco', models.TextField(db_column='tx_endereco', verbose_name='Endereco')),
                ('descricao', models.TextField(db_column='tx_descricao', verbose_name='Descricao')),
            ],
            options={
                'verbose_name': 'Destino',
                'verbose_name_plural': 'Destino',
                'db_table': 'destino',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(db_column='tx_email', max_length=100, unique=True, verbose_name='Email')),
                ('nome_completo', models.CharField(db_column='tx_nome_completo', max_length=1000, verbose_name='Nome Completo')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
                'db_table': 'usuario',
                'managed': True,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Descarte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_criacao', models.DateTimeField(db_column='dt_data_criacao', unique=True, verbose_name='Data de criacao')),
                ('peso_estimado_kg', models.FloatField(db_column='vl_peso_estimado_kg', unique=True, verbose_name='Peso Estimado')),
                ('categoria', models.CharField(db_column='tx_categoria', max_length=100, verbose_name='Categoria')),
                ('input_do_usuario', models.TextField(db_column='tx_input_do_usuario', max_length=1000, unique=True, verbose_name='Input do Usuario')),
                ('Destino', models.ForeignKey(db_column='destino_id', on_delete=django.db.models.deletion.CASCADE, related_name='descarte', to='EcoRota.destino', verbose_name='Destino')),
                ('Usuario', models.ForeignKey(db_column='usuario_id', on_delete=django.db.models.deletion.CASCADE, related_name='descarte', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Descarte',
                'verbose_name_plural': 'Descarte',
                'db_table': 'descarte',
                'managed': True,
            },
        ),
    ]
