# Generated by Django 6.1.1 on 2026-09-28 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EcoRota', '0003_alter_descarte_data_criacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='descarte',
            name='data_criacao',
            field=models.DateTimeField(auto_now_add=True, db_column='dt_data_criacao', verbose_name='Data de criacao'),
        ),
    ]
