# Generated by Django 6.1.1 on 2026-09-28 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EcoRota', '0004_alter_descarte_data_criacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='descarte',
            name='input_do_usuario',
            field=models.TextField(db_column='tx_input_do_usuario', max_length=1000, verbose_name='Input do Usuario'),
        ),
        migrations.AlterField(
            model_name='descarte',
            name='peso_estimado_kg',
            field=models.FloatField(db_column='vl_peso_estimado_kg', verbose_name='Peso Estimado'),
        ),
    ]
