# Generated by Django 6.1.1 on 2026-09-28 18:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EcoRota', '0005_alter_descarte_input_do_usuario_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='descarte',
            name='peso_estimado_kg',
            field=models.DecimalField(db_column='vl_peso_estimado_kg', decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Peso Estimado'),
        ),
    ]
